
development:
  adapter: postgresql
  database: haunted_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: haunted_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: haunted_production
  pool: 5
  timeout: 5000